###############################################################################
##
##Licensed Materials - Property of IBM
##
##(C) Copyright IBM Corp. 2021, 2026. All Rights Reserved.
##
##US Government Users Restricted Rights - Use, duplication or
##disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##
###############################################################################
apiVersion: operator.ibm.com/v1
kind: IBMServiceMeterDefinition
metadata:
  name: {% if license_prefix == 'cp4ba' %}cp4ba-cpe-metrics{% else %}ccx-{{ license_prefix }}-cpe-metrics-prod{% endif %}

  namespace: {{ namespace }}
{% if license_prefix != 'cp4ba' %}  labels:
    ccx.ibm.com/backup-type: mandatory
{% endif %}spec:
  mappingId: cpedeployment000000000001
  processing: LAST
  repeat: true
  breakdownDefs:
    - breakdownBy:
        name: INSTANCE_COUNT
      groupBy:
        - componentId
        - componentName
        - version
        - environment
        - architecture
        - platform
        - java_rpc_calls
        - dot_net_rpc_calls
        - css_objects_indexed
        - es_os_objects_created
        - db2_db_count
        - oracle_db_count
        - mssql_db_count
        - postgresql_db_count
        - asa_write_bytes
        - fcd_fcps_in_use
        - document_creates
        - propertytemplate_creates
        - choicelist_creates
        - folder_creates
        - sweep_creates
      source: metricQuantity
      processing: LAST
  data:
    componentId: {{ data.componentId }}
    componentName: {{ data.componentName }}
    productId: {{ data.productId }}
    productName: {{ data.productName }}
    metricName: {{ data.metricName }}
    metricDescription: {{ data.metricDescription }}
    metricType: {{ data.metricType }}

# Made with Bob
