kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-licensing-operator
  namespace: <NAMESPACE>
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-operator
    namespace: <NAMESPACE>
roleRef:
  kind: ClusterRole
  name: ibm-licensing-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-license-service
  namespace: <NAMESPACE>
subjects:
  - kind: ServiceAccount
    name: ibm-license-service
    namespace: <NAMESPACE>
roleRef:
  kind: ClusterRole
  name: ibm-license-service
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-license-service-cluster-monitoring-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: ibm-license-service
  namespace: <NAMESPACE>
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-license-service-restricted
  namespace: <NAMESPACE>
subjects:
  - kind: ServiceAccount
    name: ibm-license-service-restricted
    namespace: <NAMESPACE>
roleRef:
  kind: ClusterRole
  name: ibm-license-service-restricted
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-licensing-default-reader
  namespace: <NAMESPACE>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-licensing-default-reader
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-default-reader
    namespace: <NAMESPACE>