###############################################################################
##
##Licensed Materials - Property of IBM
##
##(C) Copyright IBM Corp. 2021, 2026. All Rights Reserved.
##
##US Government Users Restricted Rights - Use, duplication or
##disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##
###############################################################################
apiVersion: ccxaiservices.operator.ibm.com/v1
kind: CCXAIServices
metadata:
  name: ai-services
  labels:
    app.kubernetes.io/instance: ibm-ccx-ai-services
    app.kubernetes.io/managed-by: ibm-ccx-ai-services
    app.kubernetes.io/name: ibm-ccx-ai-services
    release: 26.0.0
spec:
  ## The version of the AI Services operator that is being used.
  appVersion: 26.0.0

  ## MUST exist, used to accept ibm license; valid value only can be "true"
  license:
    accept:

  ##############################################################
  ## Shared configuration for all Content Cortex AI components  #
  ##############################################################
  shared_configuration:
    ## This is the deployment context for Content Cortex. No update is required.
    sc_deployment_context: "FNCM"

    ## Choose the licensing model for the Product you are installing.
    ## IBM Content Cortex Essentials:
    ## - CCx.Ess.AU
    ## - CCx.Ess.EP
    ## - CCx.EE
    ## IBM Content Cortex Restricted:
    ## - CCx.AR
    ## - CCx.PR
    ## - CCx.ER
    ## IBM Cloud Pak for Business Automation:
    ## - CP4BA.NonProd
    ## - CP4BA.Prod
    ## - CP4BA.User
    sc_ccx_license_model: "<Required>"

    ## All AI Services components must use/share the image_pull_secrets to pull images.
    image_pull_secrets:
      - ibm-entitlement-key

    ## All AI Services components must use/share the same docker image repository.  For example, if IBM Entitled Registry is used, then
    ## it should be "cp.icr.io".  Otherwise, it will be a local docker registry.
    sc_image_repository: cp.icr.io

    ## Used to sign all AI Services internal certificates for internal services communications. In most cases, this value should not be changed.
    ## All AI Services components must use/share the root_ca_secret in order for integration.
    root_ca_secret: ai-services-root-ca

    ## Optional: You can specify a profile size - valid values are small,medium,large - default is small.
    sc_deployment_profile_size: "small"

    ## The platform to be deployed specified by the user.  Possible values are: OCP and other.
    sc_deployment_platform: "<Required>"

    ## If the root certificate authority (CA) key of the external service is not signed by the operator root CA key, provide the TLS certificate of
    ## the external service to the component's truststore.
    trusted_certificate_list: [ ]

    ## Provide the storage class name for the file storage provisioner.
    ## Operator will use the provided storage classes to provision required PVC volumes.
    storage_configuration:
      sc_slow_file_storage_classname: "<Required>"
