################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2026. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicensing
metadata:
  name: instance
spec:
  license:
    accept: true
  softwareCentral:
    enable: true
    entitlementKeySecret: ibm-ccx-ls-secret
  datasource: datacollector
  gatewayEnabled: true
  httpsEnable: true
  imagePullSecrets:
    - ibm-entitlement-key
  version: 4.2.21

