###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2024. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
"""
Report writer for the validate command.

Produces a plain-text (.txt) or IBM-branded PDF (.pdf) compliance report
from the results computed by validate.run().
"""

from __future__ import annotations

from calendar import month_abbr
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from urllib.parse import urlparse

from rich.console import Console

from helper_scripts.license.constants import LICENSE_TYPES
from helper_scripts.license.validate.config_loader import ServerConfig

console = Console()

# ── IBM brand colours ─────────────────────────────────────────────────────────
_IBM_BLUE   = "#0F62FE"
_IBM_RED    = "#DA1E28"
_IBM_YELLOW = "#F1C21B"
_IBM_GREEN  = "#24A148"
_LIGHT_RED    = "#FFD7D9"
_LIGHT_YELLOW = "#FCF4D6"
_LIGHT_GREEN  = "#DEFBE6"


# ── Data model ────────────────────────────────────────────────────────────────

@dataclass
class ReportData:
    generated_at: datetime
    start_date: date
    end_date: date
    servers: list[ServerConfig]
    entitlement_per_month: int
    license_counts: dict[str, int]
    months: list[tuple[int, int]]
    monthly_totals: dict[tuple[int, int], int]
    over_months: int
    total_used: int
    total_entitled: int


# ── Helpers ───────────────────────────────────────────────────────────────────

def _status_str(used: int, entitlement: int) -> str:
    if entitlement == 0 or used > entitlement:
        return "OVER QUOTA"
    pct = used / entitlement * 100
    if pct >= 90:
        return f"WARNING ({pct:.1f}%)"
    return "COMPLIANT"


def _hostname(url: str) -> str:
    """Extract just the hostname from a URL for display."""
    try:
        return urlparse(url).hostname or url
    except Exception:
        return url


# ── Plain-text writer ─────────────────────────────────────────────────────────

def _write_txt(data: ReportData, path: Path) -> None:
    lines: list[str] = []
    sep  = "=" * 72
    dash = "-" * 72

    lines += [
        sep,
        "  IBM Content Cortex — License Compliance Report",
        sep,
        f"  Generated : {data.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"  Period    : {data.start_date}  →  {data.end_date}",
        f"  Servers   : {', '.join(_hostname(s.url) for s in data.servers)}",
        "",
    ]

    # Entitlement breakdown
    lines += ["  LICENSE ENTITLEMENT BREAKDOWN", dash]
    lines.append(f"  {'License Type':<40} {'Count':>6}  {'Ops/Mo':>10}  {'Monthly Total':>14}")
    lines.append(f"  {'-'*40} {'-'*6}  {'-'*10}  {'-'*14}")
    for key, meta in LICENSE_TYPES.items():
        cnt   = data.license_counts.get(key, 0)
        ops   = meta["ops"]
        total = cnt * ops
        lines.append(f"  {meta['label']:<40} {cnt:>6}  {ops:>10,}  {total:>14,}")
    lines += [dash, f"  {'Total entitlement per month':>58}  {data.entitlement_per_month:>14,}", ""]

    # Per-month usage table
    lines += ["  MONTHLY USAGE", dash]
    lines.append(f"  {'Month':<10} {'Ops Used':>14} {'Entitlement':>14} {'Usage %':>9}  Status")
    lines.append(f"  {'-'*10} {'-'*14} {'-'*14} {'-'*9}  {'-'*20}")
    for year, month in data.months:
        used = data.monthly_totals[(year, month)]
        ent  = data.entitlement_per_month
        pct  = f"{used / ent * 100:.1f}%" if ent > 0 else "—"
        status = _status_str(used, ent)
        lines.append(
            f"  {month_abbr[month]} {year:<6} {used:>14,} {ent:>14,} {pct:>9}  {status}"
        )
    lines.append(dash)

    # Summary
    lines += [
        "",
        "  SUMMARY",
        dash,
        f"  Months checked    : {len(data.months)}",
        f"  Months over quota : {data.over_months}",
        f"  Total ops used    : {data.total_used:,}",
        f"  Total entitlement : {data.total_entitled:,}",
        dash,
        "",
        "  IBM Confidential — Generated by ccx-license-metric",
        sep,
    ]

    path.write_text("\n".join(lines), encoding="utf-8")


# ── PDF writer ────────────────────────────────────────────────────────────────

def _hex_to_rgb(hex_color: str):
    """Convert #RRGGBB to a reportlab Color."""
    from reportlab.lib.colors import HexColor
    return HexColor(hex_color)


def _write_pdf(data: ReportData, path: Path) -> None:
    from reportlab.lib import colors
    from reportlab.lib.colors import HexColor, black
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

    W, H = A4
    margin = 18 * mm

    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        leftMargin=margin, rightMargin=margin,
        topMargin=margin,  bottomMargin=margin + 8 * mm,
        title="IBM Content Cortex — License Compliance Report",
        author="ccx-license-metric",
    )

    ibm_blue   = HexColor(_IBM_BLUE)
    ibm_red    = HexColor(_IBM_RED)
    ibm_yellow = HexColor(_IBM_YELLOW)
    ibm_green  = HexColor(_IBM_GREEN)
    lt_red     = HexColor(_LIGHT_RED)
    lt_yellow  = HexColor(_LIGHT_YELLOW)
    lt_green   = HexColor(_LIGHT_GREEN)

    styles = getSampleStyleSheet()
    body   = ParagraphStyle("body",   fontName="Helvetica",      fontSize=9,  leading=13)
    bold   = ParagraphStyle("bold",   fontName="Helvetica-Bold", fontSize=9,  leading=13)
    h1     = ParagraphStyle("h1",     fontName="Helvetica-Bold", fontSize=13, leading=17, spaceAfter=4)
    h2     = ParagraphStyle("h2",     fontName="Helvetica-Bold", fontSize=10, leading=14, spaceBefore=10, spaceAfter=4)
    meta   = ParagraphStyle("meta",   fontName="Helvetica",      fontSize=8,  leading=12, textColor=colors.HexColor("#525252"))
    center = ParagraphStyle("center", fontName="Helvetica",      fontSize=9,  leading=13, alignment=TA_CENTER)

    usable_w = W - 2 * margin
    story = []

    # ── Header / footer ───────────────────────────────────────────────────────
    def _header_bar(canvas, doc):
        canvas.saveState()
        # Footer only
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.HexColor("#525252"))
        canvas.drawString(margin, 10 * mm, "IBM Confidential — Generated by ccx-license-metric")
        canvas.drawRightString(W - margin, 10 * mm, f"Page {doc.page}")
        canvas.restoreState()

    # ── Title block ───────────────────────────────────────────────────────────
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("IBM Content Cortex — License Compliance Report", h1))
    story.append(HRFlowable(width="100%", thickness=1, color=ibm_blue, spaceAfter=6))

    # Metadata
    server_hosts = ", ".join(_hostname(s.url) for s in data.servers)
    meta_rows = [
        ["Generated",  data.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")],
        ["Period",     f"{data.start_date}  →  {data.end_date}"],
        ["Servers",    server_hosts],
    ]
    meta_table = Table(meta_rows, colWidths=[32 * mm, usable_w - 32 * mm])
    meta_table.setStyle(TableStyle([
        ("FONT",       (0, 0), (0, -1), "Helvetica-Bold", 8),
        ("FONT",       (1, 0), (1, -1), "Helvetica",      8),
        ("TEXTCOLOR",  (0, 0), (-1, -1), colors.HexColor("#525252")),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 6 * mm))

    # ── Entitlement breakdown ─────────────────────────────────────────────────
    story.append(Paragraph("License Entitlement Breakdown", h2))
    ent_header = ["License Type", "Count", "Ops / Month", "Monthly Total"]
    ent_data   = [ent_header]
    for key, lmeta in LICENSE_TYPES.items():
        cnt   = data.license_counts.get(key, 0)
        ops   = lmeta["ops"]
        total = cnt * ops
        ent_data.append([lmeta["label"], str(cnt), f"{ops:,}", f"{total:,}"])
    ent_data.append(["", "", "Total per month", f"{data.entitlement_per_month:,}"])

    cw = [usable_w * 0.52, usable_w * 0.10, usable_w * 0.19, usable_w * 0.19]
    ent_table = Table(ent_data, colWidths=cw)
    ent_table.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0), ibm_blue),
        ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
        ("FONT",         (0, 0), (-1, 0), "Helvetica-Bold", 8),
        ("FONT",         (0, 1), (-1, -2), "Helvetica", 8),
        ("FONT",         (0, -1), (-1, -1), "Helvetica-Bold", 8),
        ("ALIGN",        (1, 0), (-1, -1), "RIGHT"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, colors.HexColor("#F4F4F4")]),
        ("LINEBELOW",    (0, -1), (-1, -1), 0.5, ibm_blue),
        ("TOPPADDING",   (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 3),
    ]))
    story.append(ent_table)
    story.append(Spacer(1, 6 * mm))

    # ── Per-month usage ───────────────────────────────────────────────────────
    story.append(Paragraph("Monthly Usage vs Entitlement", h2))
    usage_header = ["Month", "Ops Used", "Entitlement", "Usage %", "Status"]
    usage_data   = [usage_header]
    row_colors: list[tuple] = []

    for i, (year, month) in enumerate(data.months, start=1):
        used = data.monthly_totals[(year, month)]
        ent  = data.entitlement_per_month
        pct  = f"{used / ent * 100:.1f}%" if ent > 0 else "—"
        status = _status_str(used, ent)
        usage_data.append([f"{month_abbr[month]} {year}", f"{used:,}", f"{ent:,}", pct, status])
        if "OVER" in status:
            row_colors.append(("BACKGROUND", (0, i), (-1, i), lt_red))
        elif "WARNING" in status:
            row_colors.append(("BACKGROUND", (0, i), (-1, i), lt_yellow))
        else:
            row_colors.append(("BACKGROUND", (0, i), (-1, i), lt_green))

    cw2 = [usable_w * 0.15, usable_w * 0.18, usable_w * 0.18, usable_w * 0.12, usable_w * 0.37]
    usage_table = Table(usage_data, colWidths=cw2)
    usage_table.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0), ibm_blue),
        ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
        ("FONT",         (0, 0), (-1, 0), "Helvetica-Bold", 8),
        ("FONT",         (0, 1), (-1, -1), "Helvetica", 8),
        ("ALIGN",        (1, 0), (-1, -1), "RIGHT"),
        ("ALIGN",        (4, 0), (4, -1), "LEFT"),
        ("TOPPADDING",   (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 3),
        ("GRID",         (0, 0), (-1, -1), 0.25, colors.HexColor("#E0E0E0")),
        *row_colors,
    ]))
    story.append(usage_table)
    story.append(Spacer(1, 6 * mm))

    # ── Summary ───────────────────────────────────────────────────────────────
    story.append(Paragraph("Summary", h2))
    summary_data = [
        ["Months checked",    str(len(data.months))],
        ["Months over quota", str(data.over_months)],
        ["Total ops used",    f"{data.total_used:,}"],
        ["Total entitlement", f"{data.total_entitled:,}"],
    ]
    sum_table = Table(summary_data, colWidths=[50 * mm, usable_w - 50 * mm])
    ovr_color = ibm_red if data.over_months > 0 else ibm_green
    sum_table.setStyle(TableStyle([
        ("FONT",       (0, 0), (0, -1), "Helvetica-Bold", 9),
        ("FONT",       (1, 0), (1, -1), "Helvetica",      9),
        ("TEXTCOLOR",  (1, 1), (1, 1), ovr_color),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(sum_table)

    doc.build(story, onFirstPage=_header_bar, onLaterPages=_header_bar)


# ── Public dispatcher ─────────────────────────────────────────────────────────

def write_report(data: ReportData, fmt: str, path: str) -> None:
    """Write the compliance report in the requested format."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "txt":
        _write_txt(data, out)
    else:
        _write_pdf(data, out)
    console.print(f"\n[green]✓  Report written to {out.resolve()}[/green]")
