###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2024. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

"""
Model Gateway Artifact Generator

Generates Kubernetes artifacts for IBM Content Cortex Model Gateway:
- Custom Resource (CR) for ModelGateway — deploy_redis and deploy_postgres are
  always set to false; Model Gateway always uses the external-connection path
  (model-gateway-postgres-external-secret / model-gateway-redis-external-secret).
- model-gateway-admins-secret  (admins.json API key, required by 26.1.0 CR)

The external-connection secrets themselves are generated by GenerateCNPGRedis
(internal IBM-managed case) or left as placeholder files for the user to fill
(external/BYO case).
"""

import base64
import json
import os
import secrets
import string
from logging import Logger
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from ruamel.yaml import YAML
from ruamel.yaml.scalarstring import SingleQuotedScalarString


class GenerateModelGateway:
    """
    Generator class for Model Gateway Kubernetes artifacts.

    Generates:
    - ModelGateway Custom Resource (CR)
    - model-gateway-admins-secret (admins.json with generated apiKey)

    Note: deploy_redis and deploy_postgres are always set to false in the CR.
    Model Gateway always connects via the external-connection interface
    (model-gateway-postgres-external-secret / model-gateway-redis-external-secret).
    Those secrets are produced by GenerateCNPGRedis, not this class.
    """

    def __init__(
        self,
        model_gateway_properties: Dict,
        deployment_properties: Dict,
        namespace: str = "",
        ingress_properties: Optional[Dict] = None,
        logger: Optional[Logger] = None,
    ):
        self._logger = logger
        self._mg_properties = model_gateway_properties
        self._deployment_properties = deployment_properties
        self._ingress_properties = ingress_properties or {}
        self._namespace = namespace

        self.ccx_version = self._deployment_properties.get("CCX_Version", "26.0.1")

        # Track generated files
        self._generated_files: List[Tuple[str, Path, int]] = []

        # Setup output paths
        self._generate_folder = Path.cwd() / "generatedFiles" / self._namespace
        self._generate_folder.mkdir(parents=True, exist_ok=True)

        self._secrets_folder = self._generate_folder / "secrets"
        self._secrets_folder.mkdir(parents=True, exist_ok=True)

        # CR template path
        self._base_template = (
            Path.cwd()
            / "helper_scripts"
            / "generate"
            / "cr_templates"
            / self.ccx_version
            / "model-gateway"
            / "base.yaml"
        )

        # Output file paths
        self._generated_cr = self._generate_folder / "ibm_model_gateway_cr_production.yaml"
        self._generated_admins_secret = self._secrets_folder / "model-gateway-admins-secret.yaml"

        # YAML handler
        self._yaml = YAML()
        self._yaml.preserve_quotes = True
        self._yaml.representer.ignore_aliases = lambda *args: True

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _log_info(self, message: str):
        if self._logger:
            self._logger.info(message)

    def _log_error(self, message: str):
        if self._logger:
            self._logger.error(message)

    def _b64(self, value: str) -> str:
        return base64.b64encode(value.encode()).decode()

    @staticmethod
    def _generate_api_key(length: int = 32) -> str:
        """Generate a cryptographically secure random API key."""
        alphabet = string.ascii_letters + string.digits
        return "".join(secrets.choice(alphabet) for _ in range(length))

    # ------------------------------------------------------------------
    # CR generation helpers
    # ------------------------------------------------------------------

    def _populate_ingress(self, spec: Dict) -> None:
        """Populate ingress fields in the CR spec from ingress_properties.

        Mirrors the pattern used by GenerateAIServices._populate_ingress_section().
        Only applies when ccx_version >= 26.1.0 (the 26.0.0 CR schema does not
        have top-level ingress fields).

        The template always contains placeholder values for all four ingress keys
        so ruamel preserves their position in the output. This method overwrites
        them in-place and removes empty placeholders when ingress is disabled.
        """
        if not self._ingress_properties:
            # No ingress config — remove the empty placeholder keys entirely
            for key in ("ingress_enabled", "deployment_hostname_suffix",
                        "ingress_tls_secret_name", "ingress_annotations"):
                spec.pop(key, None)
            return

        ingress_enabled = self._ingress_properties.get("INGRESS_ENABLED", False)
        spec["ingress_enabled"] = bool(ingress_enabled)

        if ingress_enabled:
            # Hostname — only set when non-empty and not a placeholder
            hostname = str(self._ingress_properties.get("INGRESS_HOSTNAME", "") or "").strip()
            if hostname and hostname not in ("<Required>", "<Optional>"):
                spec["deployment_hostname_suffix"] = SingleQuotedScalarString(hostname.lower())
            else:
                spec.pop("deployment_hostname_suffix", None)

            # TLS secret
            if self._ingress_properties.get("INGRESS_TLS_ENABLED", False):
                tls_secret = str(
                    self._ingress_properties.get("INGRESS_TLS_SECRET_NAME", "") or ""
                ).strip()
                if tls_secret and tls_secret not in ("<Required>", "<Optional>"):
                    spec["ingress_tls_secret_name"] = SingleQuotedScalarString(tls_secret)
                else:
                    spec.pop("ingress_tls_secret_name", None)
            else:
                spec.pop("ingress_tls_secret_name", None)

            # Annotations — list of "key: value" strings → list of dictionaries
            annotations = []

            for item in self._ingress_properties.get("INGRESS_ANNOTATIONS", []) or []:
                if ":" in item:
                    item_key, item_value = item.split(":", 1)

                    # Remove leading/trailing whitespace and single quotes
                    # from the key and value
                    item_key = item_key.strip()
                    item_value = item_value.strip().strip('"').strip("\\'")

                    annotations.append({item_key: item_value})

            if annotations:
                spec["ingress_annotations"] = annotations
            else:
                spec.pop("ingress_annotations", None)
        else:
            # ingress disabled — remove all optional ingress keys
            for key in ("deployment_hostname_suffix", "ingress_tls_secret_name",
                        "ingress_annotations"):
                spec.pop(key, None)

        self._log_info(
            f"Ingress configured in Model Gateway CR: ingress_enabled={ingress_enabled}"
        )

    # ------------------------------------------------------------------
    # CR generation
    # ------------------------------------------------------------------

    def generate_cr(self) -> bool:
        """Generate the ModelGateway Custom Resource YAML."""
        try:
            if not self._base_template.exists():
                self._log_error(f"Model Gateway CR base template not found: {self._base_template}")
                return False

            with open(self._base_template) as f:
                cr = self._yaml.load(f)

            spec = cr.get("spec", {})

            # License
            spec["license"]["accept"] = True

            # Deployment platform
            spec["deployment_platform"] = SingleQuotedScalarString(
                self._deployment_properties.get("PLATFORM", "OCP")
            )

            # Image registry
            if self._deployment_properties.get("PRIVATE_REGISTRY_URL"):
                spec["docker_registry_prefix"] = SingleQuotedScalarString(
                    self._deployment_properties.get("PRIVATE_REGISTRY_URL")
                )

            # Storage — the operator Ansible role (set_storage.yaml) requires either
            # storageVendor or blockStorageClass to be set unconditionally, even when
            # deploy_postgres and deploy_redis are both false (the gate runs before
            # those flags are checked).  blockStorageClass is only consumed by the
            # postgres and redis templates, which are skipped in standalone mode, so
            # setting it to the same value as fileStorageClass is safe on clusters
            # that have no dedicated block storage class (e.g. Fyre/NFS-only).
            file_storage_class = SingleQuotedScalarString(
                str(
                    self._deployment_properties.get("FAST_FILE_STORAGE_CLASSNAME")
                    or "<Required>"
                )
            )
            spec["fileStorageClass"] = file_storage_class
            spec["blockStorageClass"] = file_storage_class

            # scaleConfig defaults to "small" in the CR template; not surfaced in
            # the MG property file — the template default is used as-is.

            # deploy_redis and deploy_postgres are always false.
            # Model Gateway always uses the external-connection interface.
            spec["deploy_redis"] = False
            spec["deploy_postgres"] = False

            # external_redis tells the operator to read the Redis URL from
            # externalRedisSecret instead of provisioning its own Redis instance.
            # We always set this to true because we own a real Redis secret
            # (model-gateway-redis-external-secret) regardless of whether the
            # backing Redis is IBM-managed or user-supplied.
            use_ibm_redis = str(self._mg_properties.get("redis", {}).get("USE_IBM_REDIS", False)).lower() in ("true", "1", "yes")
            enable_redis = use_ibm_redis or str(self._mg_properties.get("redis", {}).get("ENABLED", False)).lower() in ("true", "1", "yes")

            if enable_redis:
                spec["external_redis"] = True
                spec["externalRedisSecret"] = SingleQuotedScalarString(
                    "model-gateway-redis-external-secret"
                )
                # Do NOT set externalRedisUrlKey — the operator auto-detects
                # "redis-url-ssl" (TLS) then "redis-url" (plain) from the secret.
            else:
                spec["external_redis"] = False
                spec["externalRedisSecret"] = SingleQuotedScalarString("")

            # When using IBM-managed Redis, the operator creates a self-signed TLS cert
            # in "ibm-redis-mg-cert". externalRedisCertificateSecret is the only field
            # needed — it wires the cert into the Redis TLS connection specifically.
            #
            # Do NOT add "ibm-redis-mg-cert" to tls_ca_secrets. That list is for MG's
            # own root CA candidates. The operator picks the first entry containing both
            # tls.crt and tls.key as the MG root CA — adding the Redis cert there causes
            # MG to adopt the Redis cert as its own identity when neither
            # ibm-model-gateway-root-ca nor content-root-ca exist yet (e.g. standalone
            # deployments without Content Operator). See DBACLD-261979.
            if use_ibm_redis:
                spec["externalRedisCertificateSecret"] = SingleQuotedScalarString(
                    "ibm-redis-mg-cert"
                )

            # Ingress — only the 26.1.0+ CR schema has top-level ingress fields.
            if self.ccx_version != "26.0.0":
                self._populate_ingress(spec)

            with open(self._generated_cr, "w") as f:
                self._yaml.dump(cr, f)

            self._generated_files.append(
                ("Model Gateway CR", self._generated_cr, os.path.getsize(self._generated_cr))
            )
            self._log_info(f"Generated Model Gateway CR: {self._generated_cr}")
            return True

        except Exception as e:
            self._log_error(f"Error generating Model Gateway CR: {e}")
            if self._logger:
                self._logger.exception("Detailed error:")
            return False

    # ------------------------------------------------------------------
    # Secret generation
    # ------------------------------------------------------------------

    def generate_admins_secret(self) -> bool:
        """Generate model-gateway-admins-secret with admins.json.

        The 26.1.0 CR resolves each admin's apiKey from this secret under
        the key admins.json (a JSON array of {name, apiKey} objects).
        One entry is created per admin listed in the CR's admins.users block.

        If ADMIN_PASSWORD is set in the Model Gateway property file and is not
        a placeholder, that value is used as the apiKey verbatim so the
        customer knows the key in advance (useful for scripted environments).
        If ADMIN_PASSWORD is absent or empty, a cryptographically secure
        random 32-character key is auto-generated.
        """
        try:
            admin_user = str(self._mg_properties.get("ADMIN_USER", "admin"))
            admin_password = str(self._mg_properties.get("ADMIN_PASSWORD", "") or "").strip()
            if admin_password and admin_password not in ("<Required>", "<Optional>"):
                api_key = admin_password
                self._log_info("Using ADMIN_PASSWORD from property file for admins secret")
            else:
                api_key = self._generate_api_key()
                self._log_info("ADMIN_PASSWORD not set — auto-generating admin API key")

            admins_json = json.dumps({admin_user: {"apiKey": api_key}})

            secret: Dict = {
                "apiVersion": "v1",
                "kind": "Secret",
                "metadata": {
                    "name": "model-gateway-admins-secret",
                    "namespace": self._namespace,
                },
                "type": "Opaque",
                "data": {
                    "admins.json": self._b64(admins_json),
                },
            }

            with open(self._generated_admins_secret, "w") as f:
                self._yaml.dump(secret, f)

            self._generated_files.append(
                ("Model Gateway Admins Secret", self._generated_admins_secret,
                 os.path.getsize(self._generated_admins_secret))
            )
            self._log_info(f"Generated Model Gateway admins secret: {self._generated_admins_secret}")
            return True

        except Exception as e:
            self._log_error(f"Error generating Model Gateway admins secret: {e}")
            if self._logger:
                self._logger.exception("Detailed error:")
            return False

    # ------------------------------------------------------------------
    # Orchestration
    # ------------------------------------------------------------------

    def generate_all(self) -> bool:
        """Generate all Model Gateway artifacts. Returns True if all succeeded.

        Note: The external-connection secrets
        (model-gateway-postgres-external-secret, model-gateway-redis-external-secret)
        are generated by GenerateCNPGRedis, not here.
        """
        results = [
            self.generate_cr(),
            self.generate_admins_secret(),
        ]
        return all(results)
