###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2026. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

# ####################################################
# ##            IBM Source Registry                 ##
# ####################################################
# Images are always pulled from the IBM Entitled Registry (icr.io).
# Provide your IBM Entitlement Key below.
# See: https://www.ibm.com/docs/SSL4SY_26.0.0/com.ibm.dba.install/op_topics/tsk_images_enterp_entitled.html
ENTITLEMENT_KEY = "<IBMEntitlementKey>"

# ####################################################
# ##          Private Registry                      ##
# ####################################################
# Images are pushed to your private registry.
# All fields below are required.

# Hostname, context path and port of the private registry
# Example 1: myprivateregistry.com:5000/registrypath
# Example 2: myprivateregistry.com:5000
# Example 3: myprivateregistry.com/registrypath
PRIVATE_REGISTRY_URL = "<RegistryURL>"

PRIVATE_REGISTRY_USERNAME = "<RegistryUsername>"

PRIVATE_REGISTRY_PASSWORD = "<RegistryPassword>"

# Is your private registry using SSL - Valid values: [true; false]
PRIVATE_REGISTRY_SSL_ENABLED = true

# File path to the SSL cert of the private registry.
# Required when PRIVATE_REGISTRY_SSL_ENABLED = true.
# Certificate must be in PEM format.
# Alternatively, disable certificate verification with the --tls-verify=false flag.
PRIVATE_REGISTRY_SSL_CRT_PATH = "/path/to/my/certificate.crt"
