################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2026. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-usage-metering
    app.kubernetes.io/managed-by: ibm-usage-metering
    app.kubernetes.io/name: ibm-usage-metering
    component-id: ibm-usage-metering
  name: ibm-usage-metering-operator-sa
