###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2026 All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-ccxai
    app.kubernetes.io/managed-by: ibm-ccxai
    app.kubernetes.io/name: ibm-ccxai
    release: 26.0.0
  name: ibm-ccx-ai-services-operator-sa