################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2023. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-content-cortex-operator-catalog
  namespace: REPLACE_NAMESPACE
spec:
  displayName: IBM Content Cortex Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-content-cortex-catalog@sha256:51573de75b519d35ec2cab56dd1cafcef3bbacbd83b85d66933a5fe4f7e6635c
  grpcPodConfig:
    securityContextConfig: restricted
