################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2023. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-content-cortex-operator-catalog
  namespace: REPLACE_NAMESPACE
spec:
  displayName: IBM Content Cortex Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-content-cortex-catalog@sha256:b05261b6a1e6eef4025dfb13f77e90760002c038a3a9684707979787c19e0424
  grpcPodConfig:
    securityContextConfig: restricted
