###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2026 All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-model-gateway
    app.kubernetes.io/managed-by: ibm-model-gateway
    app.kubernetes.io/name: ibm-model-gateway
    release: 13.0.4
  name: ibm-model-gateway-operator-sa