################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2026. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operator.ibm.com/v1
kind: IBMServiceMeterDefinition
metadata:
  name: ccx-ee-graphql-metrics-prod
  namespace: REPLACE_NAMESPACE
spec:
  mappingId: graphqldeployment000000000001
  processing: LAST
  repeat: true
  breakdownDefs:
    - breakdownBy:
        name: INSTANCE_COUNT
      groupBy:
        - componentId
        - componentName
        - version
        - environment
        - architecture
        - platform
        - graphql_calls
      source: metricQuantity
      processing: LAST
  data:
    componentId: ee43abe0ed114b9a9b3412705eb77edc
    componentName: IBM Content Cortex GraphQL API
    productId: 2f16e146694e4c3eaac64ff1ec9b813e
    productName: IBM Content Cortex Essentials Employee
    metricName: INSTANCE_COUNT
    metricDescription: count of GraphQL instances
    metricType: ADOPTION
